version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: ./node_modules/.bin/eslint src/
      - run: npm test -- --coverage
      - run: npm run lint

